### ISSUE TITLE
build failed with sveltekit latest version

### ISSUE THREAD

**Issue by kenchan97** [naver/egjs-infinitegrid#505]
## Description
file:///C:/Users/LAN/Desktop/Svelte/BBS/.svelte-kit/output/server/entries/pages/HomePage.svelte.js:2
import { Renderer, CONTAINER_CLASS_NAME, INFINITEGRID_METHODS, MasonryInfiniteGrid as MasonryInfiniteGrid$1 } from "@egjs/infinitegrid";
                   ^^^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'CONTAINER_CLASS_NAME' not found. The requested module '@egjs/infinitegrid' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@egjs/infinitegrid';
const { Renderer, CONTAINER_CLASS_NAME, INFINITEGRID_METHODS, MasonryInfiniteGrid: MasonryInfiniteGrid$1 } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async Promise.all (index 0)
    at async respond$1 (file:///C:/Users/LAN/Desktop/Svelte/BBS/.svelte-kit/output/server/index.js:1945:13)
    at async resolve (file:///C:/Users/LAN/Desktop/Svelte/BBS/.svelte-kit/output/server/index.js:2333:114)
    at async respond (file:///C:/Users/LAN/Desktop/Svelte/BBS/.svelte-kit/output/server/index.js:2283:22)
    at async visit (file:///C:/Users/LAN/Desktop/Svelte/BBS/node_modules/@sveltejs/kit/dist/prerender.js:626:20)
SyntaxError: Named export 'CONTAINER_CLASS_NAME' not found. The requested module '@egjs/infinitegrid' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@egjs/infinitegrid';
const { Renderer, CONTAINER_CLASS_NAME, INFINITEGRID_METHODS, MasonryInfiniteGrid: MasonryInfiniteGrid$1 } = pkg;

SyntaxError: Named export 'CONTAINER_CLASS_NAME' not found. The requested module '@egjs/infinitegrid' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@egjs/infinitegrid';
const { Renderer, CONTAINER_CLASS_NAME, INFINITEGRID_METHODS, MasonryInfiniteGrid: MasonryInfiniteGrid$1 } = pkg;

SyntaxError: Named export 'CONTAINER_CLASS_NAME' not found. The requested module '@egjs/infinitegrid' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@egjs/infinitegrid';
const { Renderer, CONTAINER_CLASS_NAME, INFINITEGRID_METHODS, MasonryInfiniteGrid: MasonryInfiniteGrid$1 } = pkg;

SyntaxError: Named export 'CONTAINER_CLASS_NAME' not found. The requested module '@egjs/infinitegrid' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@egjs/infinitegrid';
const { Renderer, CONTAINER_CLASS_NAME, INFINITEGRID_METHODS, MasonryInfiniteGrid: MasonryInfiniteGrid$1 } = pkg;

SyntaxError: Named export 'CONTAINER_CLASS_NAME' not found. The requested module '@egjs/infinitegrid' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@egjs/infinitegrid';
const { Renderer, CONTAINER_CLASS_NAME, INFINITEGRID_METHODS, MasonryInfiniteGrid: MasonryInfiniteGrid$1 } = pkg;

file:///C:/Users/LAN/Desktop/Svelte/BBS/node_modules/@sveltejs/kit/dist/prerender.js:460
                                throw new Error(format_error(details, config));
                                      ^

Error: 500 /
    at file:///C:/Users/LAN/Desktop/Svelte/BBS/node_modules/@sveltejs/kit/dist/prerender.js:460:11
    at save (file:///C:/Users/LAN/Desktop/Svelte/BBS/node_modules/@sveltejs/kit/dist/prerender.js:744:4)
    at visit (file:///C:/Users/LAN/Desktop/Svelte/BBS/node_modules/@sveltejs/kit/dist/prerender.js:635:3)

## Steps to check or reproduce
update to latest Sveltekit
and npm run build

**Comment by daybrush** [comment]
@kenchan97 

Try `@egjs/svelte-infinitegrid@4.6.1-beta.0` version.

Thank you :)

**Comment by daybrush** [comment]
@GrassHopper42 


Try `@egjs/svelte-infinitegrid@4.6.1-beta.1` version.

Thank you

**Comment by GrassHopper42** [comment]
> @GrassHopper42
> 
> Try `@egjs/svelte-infinitegrid@4.6.1-beta.1` version.
> 
> Thank you

It works! Thank you!!!!!!

**Comment by daybrush** [comment]
@GrassHopper42 

* `@egjs/infinitegrid` 4.7.0
* `@egjs/react-infinitegrid` 4.7.0
* `@egjs/svelte-infinitegrid` 4.7.0
* `@egjs/vue-infinitegrid` 4.7.0
* `@egjs/vue3-infinitegrid` 4.7.0
* `@egjs/ngx-infinitegrid` 4.7.0


Updated to the latest version

**Comment by kenchan97** [comment]
thank your response

**Comment by msohaill** [comment]
Not sure if it is a related issue, but I receive errors with `npm run dev` but not `npm run build`. Using sveltekit v1.5.0, I get the following error in the browser console:
```
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'options.props.GridClass = MasonryInfiniteGrid')
```
This error persists regardless of the type of infinite grid used.

## To reproduce

Create sveltekit project with latest. Use [starter code](https://naver.github.io/egjs-infinitegrid/Guides#masonryinfinitegrid). Run `npm run dev`

Thank you!
